// <auto-generated />
using System;
using LIBBRARY_MANAGER.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIBBRARY_MANAGER.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20251111191347_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Book", b =>
                {
                    b.Property<long>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Loan", b =>
                {
                    b.Property<long>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Penalty")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ref_Loan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SubscriberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoanId");

                    b.HasIndex("BookId");

                    b.HasIndex("Ref_Loan")
                        .IsUnique();

                    b.HasIndex("SubscriberId");

                    b.ToTable("Loans", (string)null);
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Modification", b =>
                {
                    b.Property<long>("ModificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NewReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OldReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ref_Modification")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("StaffMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModificationId");

                    b.HasIndex("LoanId");

                    b.HasIndex("Ref_Modification")
                        .IsUnique();

                    b.HasIndex("StaffMemberId");

                    b.ToTable("Modifications", (string)null);
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.User", b =>
                {
                    b.Property<long>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse_Mail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date_Creation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password_Hash");

                    b.Property<string>("Name_User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Num_Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id_User");

                    b.HasIndex("Adresse_Mail")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.StaffMember", b =>
                {
                    b.HasBaseType("LIBBRARY_MANAGER.Model.User");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ref_Staff")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("YearHired")
                        .HasColumnType("INTEGER");

                    b.HasIndex("Ref_Staff")
                        .IsUnique();

                    b.ToTable("StaffMembers", (string)null);
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Subscriber", b =>
                {
                    b.HasBaseType("LIBBRARY_MANAGER.Model.User");

                    b.Property<decimal>("Fidelity")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ref_Subscriber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasIndex("Ref_Subscriber")
                        .IsUnique();

                    b.ToTable("Subscribers", (string)null);
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Loan", b =>
                {
                    b.HasOne("LIBBRARY_MANAGER.Model.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIBBRARY_MANAGER.Model.Subscriber", "Subscriber")
                        .WithMany("Loans")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Modification", b =>
                {
                    b.HasOne("LIBBRARY_MANAGER.Model.Loan", "Loan_")
                        .WithMany("Modifications")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LIBBRARY_MANAGER.Model.StaffMember", "StaffMember_")
                        .WithMany("Modifications")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Loan_");

                    b.Navigation("StaffMember_");
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.StaffMember", b =>
                {
                    b.HasOne("LIBBRARY_MANAGER.Model.User", null)
                        .WithOne()
                        .HasForeignKey("LIBBRARY_MANAGER.Model.StaffMember", "Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Subscriber", b =>
                {
                    b.HasOne("LIBBRARY_MANAGER.Model.User", null)
                        .WithOne()
                        .HasForeignKey("LIBBRARY_MANAGER.Model.Subscriber", "Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Loan", b =>
                {
                    b.Navigation("Modifications");
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.StaffMember", b =>
                {
                    b.Navigation("Modifications");
                });

            modelBuilder.Entity("LIBBRARY_MANAGER.Model.Subscriber", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
